### ISSUE TITLE
Considerably slower than Snappy

### ISSUE THREAD

**Issue by Awendel** [pierrec/node-lz4#114]
LZ4 on paper is meant to beat Snappy, especially with decompression.

Yet comparing this library against https://github.com/Brooooooklyn/snappy, it really is a lot slower, it doesn't even come close.

Have there been any benchmarks / tests pinpointing to why this package is so much slower?

**Comment by ankon** [comment]
Out of interest: Could you expand a bit on how measured?

**Comment by Awendel** [comment]
Sure, was considering it as compression algo for Redis DB.

Had large Array of JSON Objects (each a few kb) and then looped through, compressing & decompressing respectively and adding up the latencies. Snappy did that in like 90ms whereas node-lz4 took like around 300ms

**Comment by pierrec** [comment]
Not sure. Benchmarks are always fussy and you should choose the algorithm based on your findings.
Note that LZ4 is not very good (as in fast) for small inputs. It really shines on large ones. YMMV
