### ISSUE TITLE
"require"function is not supported in broswer

### ISSUE THREAD

**Issue by ShangBella** [pierrec/node-lz4#23]
I compressed my data in server side with lz4, it is pretty impressive and now what I want to do is to decompress my data in client side using javascript. I tried the examples you posted here. however, the "require" fucntion is not supported in browser. Do you have any suggestions?  Thank you very much.

**Comment by pierrec** [comment]
Hello,

Indeed there was a problem with the build files. I have fixed this and it should be ok now.
Update via npm and the example should work.

Cheers!
