### ISSUE TITLE
LZ4 Javascript compress function corrupts data

### ISSUE THREAD

**Issue by jorangreef** [pierrec/node-lz4#31]
I wrote a fuzz test to test node-lz4's javascript binding and came up with a 100KB file that gets corrupted by the compress function.

To reproduce, please download the test zip from here: https://www.dropbox.com/s/8pohyaskevski5m/LZ4Test.zip?dl=0

The zip contains `lz4test.js` and `lz4test.data` (100KB but very compressible)

The test expects LZ4 to already be installed in `node_modules` in the current working directory to which you extract the zip.

The test reads the data file, compresses it, uncompresses it and compares with the original. The length is the same but the contents are different.

The native binding works, and the test can test either native binding or JS binding:

```
// Test Javascript binding (FAIL):
node lz4test.js js

// Test Native binding (PASS):
node lz4test.js native
```

**Comment by jorangreef** [comment]
@pierrec have you managed to try out the test I put together?

**Comment by pierrec** [comment]
I have reproduced and found the issue.
I have just uploaded the fix. 
If you could try it out and run more fuzz tests, it would be much appreciated!

**Comment by jorangreef** [comment]
Thanks @pierrec will test it out again today.

**Comment by jorangreef** [comment]
The "&&" > "||" was it. I tested on 100,000 random buffers with various random compressible runs, and it's working fine now.

**Comment by pierrec** [comment]
Fantastic! Thanks for doing this.
