### ISSUE TITLE
compress file from web client, error with compressHC

### ISSUE THREAD

**Issue by raullucero** [pierrec/node-lz4#34]
I'm trying to compress files from the web client, i have an error when i tried to compress the file with the compressHC metho.

Let you my code
```
reader.onloadend = (function(theFile) {
    return function(e) {
      console.log(e.target.result)
      var input = new Buffer(e.target.result)    

      var output = LZ4.encode(input, { highCompression: true });
      console.log(output);
      console.log(output.length);
    }; 
})(file)
reader.readAsArrayBuffer(file)
```

the error is "this.compress is not a function"

**Comment by pierrec** [comment]
Hello,

Currently, I havent had time to implement lz4 high compression in javascript, so currently it actually defaults to the standard fast compression algorithm. For some reason, it does not for you.

Could you try disabling high compression first and seeing if it works?

**Comment by raullucero** [comment]
yeah, it works so then i'll be using the compress by default configuration, thanks pierrec
