### ISSUE TITLE
new Buffer() is deprecated, use Buffer.from()

### ISSUE THREAD

**Issue by dludwig** [pierrec/node-lz4#91]
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at Object.<anonymous> ({redacted}/node_modules/lz4/lib/static.js:9:30)

thanks

**Comment by ankon** [comment]
Having this call isn't just "annoying", but actually costs speed: NodeJS will check for each buffer constructor call whether it possibly needs to log this warning, and these checks appear in profiles in our application.
